version: "3.7"
services:
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    networks:
      - web-service-network
    restart: always
networks:
  web-service-network:
    driver: bridge